.TH VICE 1 "March 1999" VICE
.SH NAME
VICE \- Versatile Commodore Emulator and Virtual Commodore Environment
(Version 0.99)
.SH DESCRIPTION
.I VICE
is a multi\-platform emulator of the Commodore PET, CBM-II (C610),
VIC20, C64 and C128 8\-bit computers.  The emulators run as separate
programs, but have the same user interface, share the same settings
and support the same file formats.  Also some external utilities are
provided.
.P
VICE is made up of the following programs:
.TP 8
.B x64
a Commodore 64 emulator for the X Window System
.TP
.B xvic
a Commodore VIC20 emulator for the X Window System
.TP
.B xpet
a Commodore PET emulator for the X Window System
.TP
.B xcbm2
a Commodore CBM-II (C610) emulator for the X Window System
.TP
.B c1541
a stand-alone disk image maintenance utility;
.TP
.B petcat
a Commodore BASIC de-tokenizer;
.PP
The whole documentation for these programs is available in HTML
format; the main file should be installed on your system as
/usr/local/lib/VICE/doc/vice_toc.html.
.P
For up to date news about VICE, have a look at the official home page
at
.P
.RS
http://www.tu\-chemnitz.de/~fachat/vice/vice.html
.SH SEE ALSO
.BR petcat (1),
.BR c1541 (1)
.SH AUTHORS
Ettore Perazzoli <ettore@comm2000.it>
.br
Teemu Rantanen <tvr@cs.hut.fi>
.br
Andre' Fachat <fachat@physik.tu-chemnitz.de>
.br
Daniel Sladic <sladic@eecg.toronto.edu>
.br
Andreas Boose <boose@linux.rz.fh-hannover.de>
.br
Dag Lem <resid@nimrod.no>
.br
Tibor Biczo <crown@mail.matav.hu>
.br
Jouko Valta <jopi@stekt.oulu.fi>
.br
Jarkko Sonninen <sonninen@lut.fi>

with several contributions from other people around the world; see the
HTML documentation for more information.

