#line 2 "mon_lex.c"
/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)

typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 115
#define YY_END_OF_BUFFER 116
static yyconst short int yy_accept[309] =
    {   0,
       74,   74,    0,    0,   58,   58,    0,    0,  110,  110,
        0,    0,  116,  113,  114,  106,  113,   65,  113,  113,
      113,  113,   74,   72,   73,   74,  101,  113,  102,   76,
       92,   94,   90,   91,   93,  113,   95,  113,   77,   78,
      113,  113,  113,  113,  113,  113,  115,  115,   58,   56,
       55,   31,   49,   58,   22,   50,   58,   15,   58,   17,
       58,   58,   31,   58,   58,   47,   25,   58,   19,   58,
       58,   58,   45,   35,   68,   67,   66,  109,  110,  108,
      111,  112,  114,  106,   99,   70,   75,  104,   83,   85,
       86,   84,   89,   82,   81,    0,   71,   74,    0,   72,

       73,  100,   98,  103,   79,   80,   96,   97,   64,    0,
        0,   59,    0,    0,  105,    0,   58,   58,    5,    6,
       54,   58,   58,   58,   58,   29,   58,   58,   58,   58,
       58,   58,   58,   58,   38,   58,   58,   58,   58,   58,
       58,   58,   58,   58,   58,   58,   58,    7,   58,   58,
       58,   67,  109,  110,  111,   87,   88,   69,    0,   60,
        0,    0,  107,   58,   58,   58,   58,   58,   58,   58,
       58,   58,   58,   58,   58,   58,   58,   58,   58,   58,
       58,   58,   58,   58,   58,   58,   58,   58,   58,   58,
       58,   58,   58,   58,   58,   58,   58,   58,   62,    0,

        0,    1,   58,   58,   58,   58,   58,   58,   58,   58,
       58,   58,    8,   40,   58,   46,   16,   24,   57,   18,
       58,   12,   21,    9,   58,   48,   58,   58,   58,   13,
       58,   10,   58,   58,   58,   58,   58,   58,   58,   63,
        0,    2,   32,   39,   58,   58,   58,   58,   58,   58,
       58,   58,   58,   51,   58,   58,   58,   58,   58,   33,
       58,   58,   58,   34,   58,   61,   58,   58,   58,   42,
       52,   58,   58,   36,   11,   58,   58,    4,    3,   53,
       58,   41,   14,   58,   44,   23,   58,   37,   58,   58,
       58,   58,   58,   58,   58,   58,   58,   20,   58,   43,

       58,   27,   26,   58,   58,   28,   30,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    1,    7,    8,    9,    1,    1,
        1,    1,   10,    1,    1,   11,    1,   12,   13,   14,
       14,   14,   14,   14,   14,   15,   15,    1,    1,   16,
       17,   18,   19,   20,   21,   22,   23,   24,   25,   25,
       26,   27,   26,   26,   26,   26,   28,   26,   29,   30,
       26,   26,   31,   32,   26,   26,   26,   33,   34,   26,
        1,    1,    1,    1,    1,    1,   35,   36,   37,   38,

       39,   40,   41,   42,   43,   26,   44,   45,   46,   47,
       48,   49,   50,   51,   52,   53,   54,   55,   56,   57,
       58,   26,    1,   59,    1,   60,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[61] =
    {   0,
        1,    2,    3,    4,    1,    1,    1,    1,    1,    1,
        1,    5,    5,    5,    5,    1,    1,    1,    1,    2,
        5,    5,    5,    5,    5,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    5,    5,    5,    5,    5,    5,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    1,    2
    } ;

static yyconst short int yy_base[320] =
    {   0,
        0,    0,  460,  459,   60,    0,  120,  180,  130,  139,
      461,  460,  462,  467,  142,  467,  444,  467,    0,  135,
      451,  142,  144,  149,  154,  180,  442,  441,  440,  467,
      467,  467,  467,  467,  467,  433,  425,  154,  467,  467,
      414,  405,  131,  399,  403,  391,  467,    0,    0,    0,
      467,    0,    0,  167,  165,  166,  159,  406,  400,  116,
      163,  399,  398,  406,  393,  389,  403,  172,  390,  161,
      401,  177,    0,  467,  467,    0,  467,    0,  220,  467,
        0,  467,  229,  467,  467,    0,  141,  467,  467,  467,
      467,  467,  467,  467,  467,  196,  222,  229,    0,  233,

      237,  467,  467,  467,  467,  467,  467,  467,  467,  404,
      398,  467,  389,  395,  467,  429,    0,  206,  215,    0,
        0,  209,  212,  382,  377,    0,  386,  396,  387,  384,
      375,  382,  379,  378,    0,  389,  368,  365,  378,  377,
      224,  364,  380,  378,  364,  380,  376,    0,  362,  359,
      368,    0,    0,  225,    0,  467,  467,    0,  372,  467,
      358,  367,  467,  363,  363,  370,  356,  214,  365,  363,
      358,  227,  353,  350,  362,  344,  351,  347,  345,  340,
      344,  353,  351,  336,  341,  334,  348,  342,  330,  344,
      343,  332,  327,  227,  325,  335,  340,  323,  467,  336,

      329,    0,  336,  328,  324,  335,  334,  325,  314,  329,
      329,  319,    0,    0,  318,    0,    0,    0,    0,    0,
      311,    0,    0,    0,  308,    0,  308,  307,  307,    0,
      317,    0,  317,  316,  302,  307,  312,  309,  311,  467,
      310,    0,    0,    0,  301,  296,  293,  306,  305,  298,
      307,  302,  301,    0,  290,  285,  290,  279,  289,    0,
      294,  284,  274,    0,  279,  467,  292,  290,  285,    0,
        0,  288,  268,    0,    0,  290,  282,    0,    0,    0,
      276,    0,    0,  258,    0,    0,  258,    0,  252,  238,
      222,  221,  236,  223,  211,  229,  214,    0,  201,    0,

      172,    0,    0,  137,  133,    0,    0,  467,  277,  283,
      289,  295,  130,  297,  303,  306,  312,  318,  119
    } ;

static yyconst short int yy_def[320] =
    {   0,
      308,    1,  309,  309,  308,    5,  310,  310,  311,  311,
      312,  312,  308,  308,  308,  308,  308,  308,  313,  308,
      308,  308,  308,  308,  308,  308,  308,  308,  308,  308,
      308,  308,  308,  308,  308,  308,  308,  308,  308,  308,
      308,  308,  308,  308,  308,  308,  308,  314,  315,  315,
      308,  315,  315,  315,  315,  315,  315,  315,  315,  315,
      315,  315,  315,  315,  315,  315,  315,  315,  315,  315,
      315,  315,  315,  308,  308,  316,  308,  317,  308,  308,
      318,  308,  308,  308,  308,  313,  308,  308,  308,  308,
      308,  308,  308,  308,  308,  308,  308,  308,  319,  308,

      308,  308,  308,  308,  308,  308,  308,  308,  308,  308,
      308,  308,  308,  308,  308,  314,  315,  315,  315,  315,
      315,  315,  315,  315,  315,  315,  315,  315,  315,  315,
      315,  315,  315,  315,  315,  315,  315,  315,  315,  315,
      315,  315,  315,  315,  315,  315,  315,  315,  315,  315,
      315,  316,  317,  308,  318,  308,  308,  319,  308,  308,
      308,  308,  308,  315,  315,  315,  315,  315,  315,  315,
      315,  315,  315,  315,  315,  315,  315,  315,  315,  315,
      315,  315,  315,  315,  315,  315,  315,  315,  315,  315,
      315,  315,  315,  315,  315,  315,  315,  315,  308,  308,

      308,  315,  315,  315,  315,  315,  315,  315,  315,  315,
      315,  315,  315,  315,  315,  315,  315,  315,  315,  315,
      315,  315,  315,  315,  315,  315,  315,  315,  315,  315,
      315,  315,  315,  315,  315,  315,  315,  315,  315,  308,
      308,  315,  315,  315,  315,  315,  315,  315,  315,  315,
      315,  315,  315,  315,  315,  315,  315,  315,  315,  315,
      315,  315,  315,  315,  315,  308,  315,  315,  315,  315,
      315,  315,  315,  315,  315,  315,  315,  315,  315,  315,
      315,  315,  315,  315,  315,  315,  315,  315,  315,  315,
      315,  315,  315,  315,  315,  315,  315,  315,  315,  315,

      315,  315,  315,  315,  315,  315,  315,    0,  308,  308,
      308,  308,  308,  308,  308,  308,  308,  308,  308
    } ;

static yyconst short int yy_nxt[528] =
    {   0,
       14,   15,   16,   15,   17,   18,   19,   20,   21,   14,
       22,   23,   24,   25,   26,   27,   28,   29,   14,   14,
       30,   31,   32,   33,   14,   14,   34,   14,   35,   36,
       37,   38,   39,   40,   14,   14,   14,   14,   14,   14,
       14,   14,   41,   14,   42,   14,   14,   43,   14,   14,
       14,   44,   45,   14,   14,   14,   14,   14,   46,   14,
       49,   47,   47,   47,   49,   49,   49,   49,   49,   49,
       49,   49,   49,   49,   49,   49,   49,   49,   50,   51,
       49,   49,   49,   49,   49,   49,   49,   52,   49,   49,
       49,   49,   49,   49,   53,   54,   55,   56,   57,   58,

       59,   60,   61,   49,   62,   63,   64,   49,   65,   66,
       67,   68,   69,   70,   71,   72,   73,   49,   49,   74,
       47,   47,   75,  158,   47,   77,   47,   47,   47,   47,
       47,   79,   80,   79,   86,   47,   47,   47,   47,   47,
       79,   80,   79,   83,   84,   83,   87,   87,   89,   90,
       91,   92,   87,   87,  132,   97,   97,   97,   98,   93,
      100,  100,  101,   98,   94,  101,  101,  101,   98,  133,
      111,  307,   95,   96,  107,  306,   99,  112,   47,   47,
       47,   47,   75,  108,   47,   77,   47,   47,   47,   47,
       47,   98,   98,   98,   98,   47,   47,   47,   47,   47,

       99,  118,  121,  134,  123,  128,  142,  147,  124,  148,
      135,  150,  122,  125,  143,  129,  156,  119,  126,  127,
      305,  154,  120,  154,  144,  157,  154,  151,  154,  145,
       83,   84,   83,   97,   97,   97,   98,  304,   47,   47,
       98,   98,   98,   98,  100,  100,  101,   98,  101,  101,
      101,   98,  164,  166,  168,  169,  170,  165,  187,  206,
      167,  211,  207,  234,  188,  303,  171,  302,  301,  300,
      299,  298,  297,  235,  296,  212,  189,   47,   47,   47,
       47,   47,   47,   76,   76,   76,   76,   76,   76,   78,
       78,   78,   78,   78,   78,   81,   81,   81,   81,   81,

       81,  116,  116,  117,  295,  294,  293,  117,  117,  152,
      152,  152,  153,  153,  292,  153,  153,  153,  155,  155,
      291,  155,  155,  155,  290,  289,  288,  287,  286,  285,
      284,  283,  282,  281,  280,  279,  278,  277,  276,  275,
      274,  273,  272,  271,  270,  269,  268,  267,  266,  265,
      264,  263,  262,  261,  260,  259,  258,  257,  256,  255,
      254,  253,  252,  251,  250,  249,  248,  247,  246,  245,
      244,  243,  242,  241,  240,  239,  238,  237,  236,  233,
      232,  231,  230,  229,  228,  227,  226,  225,  224,  223,
      222,  221,  220,  219,  218,  217,  216,  215,  214,  213,

      210,  209,  208,  205,  204,  203,  202,  201,  200,  199,
      198,  197,  196,  195,  194,  193,  192,  191,  190,  186,
      185,  184,  183,  182,  181,  180,  179,  178,  177,  176,
      175,  174,  173,  172,  163,  162,  161,  160,  159,  149,
      146,  141,  140,  139,  138,  137,  136,  131,  130,  115,
      114,  113,  110,  109,  106,  105,  104,  103,  102,   88,
       85,  308,   82,   82,   48,   48,   13,  308,  308,  308,
      308,  308,  308,  308,  308,  308,  308,  308,  308,  308,
      308,  308,  308,  308,  308,  308,  308,  308,  308,  308,
      308,  308,  308,  308,  308,  308,  308,  308,  308,  308,

      308,  308,  308,  308,  308,  308,  308,  308,  308,  308,
      308,  308,  308,  308,  308,  308,  308,  308,  308,  308,
      308,  308,  308,  308,  308,  308,  308
    } ;

static yyconst short int yy_chk[528] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,

        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        7,    7,    7,  319,    7,    7,    7,    7,    7,    7,
        7,    9,    9,    9,  313,    7,    7,    7,    7,    7,
       10,   10,   10,   15,   15,   15,   20,   20,   22,   22,
       22,   22,   87,   87,   60,   23,   23,   23,   23,   22,
       24,   24,   24,   24,   22,   25,   25,   25,   25,   60,
       43,  305,   22,   22,   38,  304,   23,   43,    7,    7,
        8,    8,    8,   38,    8,    8,    8,    8,    8,    8,
        8,   26,   26,   26,   26,    8,    8,    8,    8,    8,

       23,   54,   55,   61,   56,   57,   68,   70,   56,   70,
       61,   72,   55,   56,   68,   57,   96,   54,   56,   56,
      301,   79,   54,   79,   68,   96,  154,   72,  154,   68,
       83,   83,   83,   97,   97,   97,   97,  299,    8,    8,
       98,   98,   98,   98,  100,  100,  100,  100,  101,  101,
      101,  101,  118,  119,  122,  122,  123,  118,  141,  168,
      119,  172,  168,  194,  141,  297,  123,  296,  295,  294,
      293,  292,  291,  194,  290,  172,  141,  309,  309,  309,
      309,  309,  309,  310,  310,  310,  310,  310,  310,  311,
      311,  311,  311,  311,  311,  312,  312,  312,  312,  312,

      312,  314,  314,  315,  289,  287,  284,  315,  315,  316,
      316,  316,  317,  317,  281,  317,  317,  317,  318,  318,
      277,  318,  318,  318,  276,  273,  272,  269,  268,  267,
      265,  263,  262,  261,  259,  258,  257,  256,  255,  253,
      252,  251,  250,  249,  248,  247,  246,  245,  241,  239,
      238,  237,  236,  235,  234,  233,  231,  229,  228,  227,
      225,  221,  215,  212,  211,  210,  209,  208,  207,  206,
      205,  204,  203,  201,  200,  198,  197,  196,  195,  193,
      192,  191,  190,  189,  188,  187,  186,  185,  184,  183,
      182,  181,  180,  179,  178,  177,  176,  175,  174,  173,

      171,  170,  169,  167,  166,  165,  164,  162,  161,  159,
      151,  150,  149,  147,  146,  145,  144,  143,  142,  140,
      139,  138,  137,  136,  134,  133,  132,  131,  130,  129,
      128,  127,  125,  124,  116,  114,  113,  111,  110,   71,
       69,   67,   66,   65,   64,   63,   62,   59,   58,   46,
       45,   44,   42,   41,   37,   36,   29,   28,   27,   21,
       17,   13,   12,   11,    4,    3,  308,  308,  308,  308,
      308,  308,  308,  308,  308,  308,  308,  308,  308,  308,
      308,  308,  308,  308,  308,  308,  308,  308,  308,  308,
      308,  308,  308,  308,  308,  308,  308,  308,  308,  308,

      308,  308,  308,  308,  308,  308,  308,  308,  308,  308,
      308,  308,  308,  308,  308,  308,  308,  308,  308,  308,
      308,  308,  308,  308,  308,  308,  308
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "mon_cli.l"
#define INITIAL 0
#line 2 "mon_cli.l"

/* Lexer for x64 monitor */
#include <assert.h>
#include <string.h>
#include "vice.h"
#include "types.h"
#include "mon.h"
#include "mon_parse.h"

YY_BUFFER_STATE my_state;
#define min(a,b) ((a) < (b) ? (a) : (b))

int yywrap();

int new_cmd = 1, quote = 0, rol = 0, set_rol = 0;
int opt_asm = 0;
extern char *myinput;

int resolve_datatype(unsigned guess_type, char *num, int *val);

#define FNAME 1
#define CMD 2
#define STR 3
#define ROL 4
#define ASM_MODE 5

#line 611 "mon_lex.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 26 "mon_cli.l"



   if (new_cmd) {
      BEGIN CMD;
      new_cmd = 0;
   }
   if (rol) {
      BEGIN ROL;
      rol = 0;
   }
   if (asm_mode && !opt_asm) {
      BEGIN ASM_MODE;
   }


#line 779 "mon_lex.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 309 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 467 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
#line 43 "mon_cli.l"
case 2:
YY_RULE_SETUP
#line 43 "mon_cli.l"
{ BEGIN INITIAL; fprintf(mon_output, "Not yet supported: %s\n", yytext); return COMMAND_NAME; }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 45 "mon_cli.l"
{ BEGIN INITIAL; return CMD_SIDEFX; }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 46 "mon_cli.l"
{ BEGIN INITIAL; return CMD_RETURN; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 47 "mon_cli.l"
{ BEGIN INITIAL; return CMD_BLOCK_READ; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 48 "mon_cli.l"
{ BEGIN INITIAL; return CMD_BLOCK_WRITE; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 49 "mon_cli.l"
{ BEGIN INITIAL; return CMD_UP; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 50 "mon_cli.l"
{ BEGIN INITIAL; return CMD_DOWN; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 51 "mon_cli.l"
{ BEGIN INITIAL; return CMD_NEXT; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 52 "mon_cli.l"
{ BEGIN INITIAL; return CMD_STEP; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 53 "mon_cli.l"
{ BEGIN INITIAL; return CMD_IGNORE; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 54 "mon_cli.l"
{ BEGIN FNAME; return CMD_LOAD; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 55 "mon_cli.l"
{ BEGIN FNAME; return CMD_SAVE; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 56 "mon_cli.l"
{ BEGIN FNAME; return CMD_VERIFY; }
	YY_BREAK
case 15:
#line 58 "mon_cli.l"
case 16:
YY_RULE_SETUP
#line 58 "mon_cli.l"
{ BEGIN INITIAL; return CMD_FILL; }
	YY_BREAK
case 17:
#line 60 "mon_cli.l"
case 18:
YY_RULE_SETUP
#line 60 "mon_cli.l"
{ BEGIN INITIAL; return CMD_HUNT; }
	YY_BREAK
case 19:
#line 62 "mon_cli.l"
case 20:
#line 63 "mon_cli.l"
case 21:
YY_RULE_SETUP
#line 63 "mon_cli.l"
{ BEGIN INITIAL; return CMD_MOVE; }
	YY_BREAK
case 22:
#line 65 "mon_cli.l"
case 23:
YY_RULE_SETUP
#line 65 "mon_cli.l"
{ BEGIN INITIAL; return CMD_COMPARE; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 66 "mon_cli.l"
{ BEGIN INITIAL; return CMD_GOTO; }
	YY_BREAK
case 25:
#line 68 "mon_cli.l"
case 26:
YY_RULE_SETUP
#line 68 "mon_cli.l"
{ BEGIN INITIAL; return CMD_REGISTERS; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 69 "mon_cli.l"
{ BEGIN INITIAL; return CMD_READSPACE; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 70 "mon_cli.l"
{ BEGIN INITIAL; return CMD_WRITESPACE; }
	YY_BREAK
case 29:
#line 72 "mon_cli.l"
case 30:
YY_RULE_SETUP
#line 72 "mon_cli.l"
{ BEGIN INITIAL; return CMD_DISPLAYTYPE; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 73 "mon_cli.l"
{ BEGIN INITIAL; return CMD_MEM_DISPLAY; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 74 "mon_cli.l"
{ BEGIN INITIAL; return CMD_BREAK; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 75 "mon_cli.l"
{ BEGIN INITIAL; return CMD_TRACE; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 76 "mon_cli.l"
{ BEGIN INITIAL; return CMD_WATCH; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 77 "mon_cli.l"
{ BEGIN INITIAL; return CONVERT_OP; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 78 "mon_cli.l"
{ BEGIN INITIAL; yylval.i = e_ON; return CMD_BREAKPT_ONOFF; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 79 "mon_cli.l"
{ BEGIN INITIAL; yylval.i = e_OFF; return CMD_BREAKPT_ONOFF; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 80 "mon_cli.l"
{ BEGIN INITIAL; return CMD_IO; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 81 "mon_cli.l"
{ BEGIN INITIAL; return CMD_BRMON; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 82 "mon_cli.l"
{ BEGIN INITIAL; return CMD_DUMP; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 83 "mon_cli.l"
{ BEGIN INITIAL; return CMD_UNDUMP; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 84 "mon_cli.l"
{ BEGIN INITIAL; return CMD_DELETE; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 85 "mon_cli.l"
{ BEGIN INITIAL; return CMD_CONDITION; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 86 "mon_cli.l"
{ BEGIN INITIAL; return CMD_COMMAND; }
	YY_BREAK
case 45:
#line 88 "mon_cli.l"
case 46:
YY_RULE_SETUP
#line 88 "mon_cli.l"
{ BEGIN INITIAL; return CMD_EXIT; }
	YY_BREAK
case 47:
#line 90 "mon_cli.l"
case 48:
YY_RULE_SETUP
#line 90 "mon_cli.l"
{ BEGIN INITIAL; return CMD_QUIT; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 91 "mon_cli.l"
{ BEGIN INITIAL; opt_asm = 1; return CMD_ASSEMBLE; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 92 "mon_cli.l"
{ BEGIN INITIAL; return CMD_DISASSEMBLE; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 93 "mon_cli.l"
{ BEGIN INITIAL; return CMD_PRINT; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 94 "mon_cli.l"
{ BEGIN INITIAL; return CMD_DEVICE; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 95 "mon_cli.l"
{ BEGIN ROL; return CMD_SYSTEM; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 96 "mon_cli.l"
{ BEGIN ROL; return CMD_CHDIR; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 97 "mon_cli.l"
{ BEGIN ROL; return CMD_DISK; }
	YY_BREAK
case 56:
#line 100 "mon_cli.l"
case 57:
YY_RULE_SETUP
#line 100 "mon_cli.l"
{ BEGIN INITIAL; return CMD_HELP; }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 101 "mon_cli.l"
{ BEGIN INITIAL; new_cmd = 1; return BAD_CMD; }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 103 "mon_cli.l"
{ yylval.i = e_ON; return TOGGLE; }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 104 "mon_cli.l"
{ yylval.i = e_OFF; return TOGGLE; }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 105 "mon_cli.l"
{ yylval.i = e_TOGGLE; return TOGGLE; }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 107 "mon_cli.l"
{ yylval.i = e_load; return MEM_OP; }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 108 "mon_cli.l"
{ yylval.i = e_store; return MEM_OP; }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 110 "mon_cli.l"
{ return IF; }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 112 "mon_cli.l"
{ if (!quote) {
                     quote = 1;
                     BEGIN STR;
                  }
                }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 117 "mon_cli.l"
{ if (quote) {
                     quote = 0;
                     BEGIN INITIAL;
                  }
                }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 122 "mon_cli.l"
{ yylval.str = strdup(yytext); return STRING; }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 123 "mon_cli.l"
{ puts("ERROR:"); exit(-1); }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 125 "mon_cli.l"
{ yylval.i = strtol(yytext, NULL, 16);
                    return H_NUMBER;
                  }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 129 "mon_cli.l"
{ yylval.i = strtol(yytext+1, NULL, 16);
                 return H_NUMBER;
               }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 133 "mon_cli.l"
{ yylval.i = strtol(yytext, NULL, 8);
           return O_NUMBER;
         }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 137 "mon_cli.l"
{ return resolve_datatype(B_NUMBER, yytext, &(yylval.i)); }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 139 "mon_cli.l"
{ return resolve_datatype(O_NUMBER, yytext, &(yylval.i)); }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 141 "mon_cli.l"
{ return resolve_datatype(D_NUMBER, yytext, &(yylval.i)); }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 143 "mon_cli.l"
{ yylval.i = strtol(yytext+1, NULL, 2);
         return B_NUMBER;
       }
	YY_BREAK
/* [.*]+ { return B_DATA; } */
case 76:
YY_RULE_SETUP
#line 150 "mon_cli.l"
{ yylval.i = e_A; return REGISTER; }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 151 "mon_cli.l"
{ yylval.i = e_X; return REGISTER; }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 152 "mon_cli.l"
{ yylval.i = e_Y; return REGISTER; }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 153 "mon_cli.l"
{ yylval.i = e_PC; return REGISTER; }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 154 "mon_cli.l"
{ yylval.i = e_SP; return REGISTER; }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 156 "mon_cli.l"
{ yylval.i = e_sprite; return INPUT_SPEC; }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 157 "mon_cli.l"
{ yylval.i = e_character; return INPUT_SPEC; }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 158 "mon_cli.l"
{ yylval.i = e_hexadecimal; return INPUT_SPEC; }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 159 "mon_cli.l"
{ yylval.i = e_decimal; return INPUT_SPEC; }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 160 "mon_cli.l"
{ yylval.i = e_binary; return INPUT_SPEC; }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 161 "mon_cli.l"
{ yylval.i = e_octal; return INPUT_SPEC; }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 162 "mon_cli.l"
{ yylval.i = e_text_ascii; return INPUT_SPEC; }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 163 "mon_cli.l"
{ yylval.i = e_text_petscii; return INPUT_SPEC; }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 164 "mon_cli.l"
{ yylval.i = e_6502_asm; return INPUT_SPEC; }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 166 "mon_cli.l"
{ yylval.i = e_decimal; return DATA_TYPE; }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 167 "mon_cli.l"
{ yylval.i = e_hexadecimal; return DATA_TYPE; }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 168 "mon_cli.l"
{ yylval.i = e_binary; return DATA_TYPE; }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 169 "mon_cli.l"
{ yylval.i = e_octal; return DATA_TYPE; }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 170 "mon_cli.l"
{ yylval.i = e_character; return DATA_TYPE; }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 171 "mon_cli.l"
{ yylval.i = e_sprite; return DATA_TYPE; }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 172 "mon_cli.l"
{ yylval.i = e_text_ascii; return DATA_TYPE; }
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 173 "mon_cli.l"
{ yylval.i = e_text_petscii; return DATA_TYPE; }
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 175 "mon_cli.l"
{ yylval.i = e_EQU; return COMPARE_OP; }
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 176 "mon_cli.l"
{ yylval.i = e_NEQ; return COMPARE_OP; }
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 177 "mon_cli.l"
{ yylval.i = e_LTE; return COMPARE_OP; }
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 178 "mon_cli.l"
{ yylval.i = e_LT;  return COMPARE_OP; }
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 179 "mon_cli.l"
{ yylval.i = e_GT;  return COMPARE_OP; }
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 180 "mon_cli.l"
{ yylval.i = e_GTE; return COMPARE_OP; }
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 181 "mon_cli.l"
{ yylval.i = e_AND; return COMPARE_OP; }
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 182 "mon_cli.l"
{ yylval.i = e_OR;  return COMPARE_OP; }
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 185 "mon_cli.l"
{ new_cmd = 1; return TRAIL; }
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 188 "mon_cli.l"
{ yytext[yyleng-1] = '\0';
                   yylval.str = strdup(yytext+1);
                   BEGIN INITIAL; return FILENAME; }
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 192 "mon_cli.l"
{ new_cmd = 1; opt_asm = 0; return TRAIL; }
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 193 "mon_cli.l"
{ yylval.str = strdup(yytext); return R_O_L; }
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 194 "mon_cli.l"

	YY_BREAK
case 111:
YY_RULE_SETUP
#line 196 "mon_cli.l"
{ yylval.str = strdup(yytext); return ASM_LINE; }
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 197 "mon_cli.l"
{ yylval.str = NULL; return TRAIL; }
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 199 "mon_cli.l"
{ return yytext[0]; }
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 200 "mon_cli.l"

	YY_BREAK
case 115:
YY_RULE_SETUP
#line 202 "mon_cli.l"
ECHO;
	YY_BREAK
#line 1423 "mon_lex.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(FNAME):
case YY_STATE_EOF(CMD):
case YY_STATE_EOF(STR):
case YY_STATE_EOF(ROL):
case YY_STATE_EOF(ASM_MODE):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 309 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 309 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 308);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 202 "mon_cli.l"


int resolve_datatype(unsigned guess_type, char *num, int *val)
{
   if (default_datatype == e_hexadecimal) {
      *val = strtol(num, NULL, 16);
      return H_NUMBER;
   }

   if ((guess_type == D_NUMBER) || (default_datatype == e_decimal)) {
      *val = strtol(num, NULL, 10);
      return D_NUMBER;
   }

   if ((guess_type == O_NUMBER) || (default_datatype == e_octal)) {
      *val = strtol(num, NULL, 8);
      return O_NUMBER;
   }
   
   *val = strtol(num, NULL, 2);
   return B_NUMBER;
}

void free_buffer()
{
   yy_delete_buffer(my_state);
}

void make_buffer(char *str)
{
    my_state = yy_scan_buffer(str, strlen(str) + 2);
    assert(my_state);
}

int yywrap() { return 1; }
