/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define YY_USES_REJECT
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 95
#define YY_END_OF_BUFFER 96
static yyconst short int yy_acclist[356] =
    {   0,
       24,   89,   24,   89,   24,   24,   24,   24,   11,   24,
       11,   24,   24,   24,   24,   89,   24,   89,   24,   89,
       24,   89,   24,   24,   24,   27,   24,   27,   23,   24,
       23,   24,   96,   94,   95,   24,   95,   25,   94,   95,
        9,   94,   95,   94,   95,   94,   95,   94,   95,   94,
       95,   94,   95,   89,   91,   93,   94,   95,   86,   89,
       91,   93,   94,   95,   91,   93,   94,   95,   91,   93,
       94,   95,    2,   94,   95,   93,   94,   95,   18,   93,
       94,   95,   93,   94,   95,   16,   93,   94,   95,   17,
       94,   95,   19,   94,   95,   94,   95,   94,   95,   94,

       95,   94,   95,   94,   95,   94,   95,    1,   94,   95,
       11,   94,   95,   11,   24,   95,   10,   94,   95,   28,
       94,   95,   84,   94,   95,   82,   94,   95,   83,   94,
       95,   81,   94,   95,   94,   95,   91,   93,   94,   95,
       85,   94,   95,   93,   94,   95,16456,   73,   93,   94,
       95,   74,   93,   94,   95,   75,   93,   94,   95,   76,
       93,   94,   95,   93,   94,   95,   94,   95,   77,   94,
       95,   94,   95,   78,   94,   95,   79,   94,   95,   80,
       94,   95,   93,   94,   95,16456,   73,   93,   94,   95,
       75,   93,   94,   95,   77,   94,   95,   94,   95,   94,

       95,   94,   95,   49,   94,   95,   50,   94,   95,   48,
       94,   95,   94,   95,   38,   94,   95,   94,   95,   39,
       94,   95,   94,   95,   34,   94,   95,   29,   94,   95,
       94,   95,   94,   95,   30,   94,   95,   31,   94,   95,
       27,   94,   95,   27,   94,   95,   27,   94,   95,   27,
       94,   95,   23,   94,   95,   24,   92,   87,   88,   90,
       12,   14,   15,   13,   71,   70,   71,   89,   91,   93,
       91,   93,   93,   86,   89,   91,   93,   21,   22,   20,
        8,    3,    1,   11,   11,   24,   28, 8264,   69,   93,
       59,   69,   93,   69,   60,   69,   93,   61,   69,   93,

       62,   69,   63,   69,   66,   69,   63,   69,   66,   69,
       36,   41,   43,   44,   45,   37,   35,   40,   42,   32,
       33,   27,   23,   71,   70,   71,    4,   26,   69,   93,
       69,   64,   69,   65,   69,   67,   69,   68,   69,   46,
       47,    6,   69,   93,   69,    7,   55,    5,   51,   58,
       56,   57,   54,   53,   52
    } ;

static yyconst short int yy_accept[201] =
    {   0,
        1,    3,    5,    6,    7,    8,    9,   11,   13,   14,
       15,   17,   19,   21,   23,   24,   25,   27,   29,   31,
       33,   34,   36,   38,   41,   44,   46,   48,   50,   52,
       54,   59,   65,   69,   73,   76,   79,   83,   86,   90,
       93,   96,   98,  100,  102,  104,  106,  108,  111,  114,
      117,  120,  123,  126,  129,  132,  135,  137,  141,  144,
      148,  152,  156,  160,  164,  167,  169,  172,  174,  177,
      180,  183,  187,  191,  195,  198,  200,  202,  204,  207,
      210,  213,  215,  218,  220,  223,  225,  228,  231,  233,
      235,  238,  241,  244,  247,  250,  253,  256,  257,  258,

      259,  260,  261,  262,  263,  264,  265,  266,  268,  271,
      273,  274,  278,  279,  280,  281,  282,  282,  282,  283,
      283,  283,  283,  284,  285,  287,  288,  288,  289,  291,
      294,  295,  298,  301,  303,  305,  307,  309,  311,  312,
      313,  314,  314,  314,  315,  316,  317,  318,  319,  320,
      321,  322,  323,  324,  325,  327,  327,  328,  328,  328,
      329,  329,  331,  332,  334,  336,  338,  340,  341,  342,
      343,  343,  343,  343,  343,  343,  345,  346,  347,  347,
      347,  348,  348,  348,  348,  349,  349,  349,  350,  351,
      352,  352,  352,  352,  353,  354,  354,  355,  356,  356

    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    7,    8,    9,   10,    1,   11,
       12,    1,   13,   14,    1,   15,    1,   16,   17,   18,
       18,   18,   18,   18,   18,   19,   20,   21,   22,   23,
       24,   25,   26,   26,   27,   28,   29,   30,   31,   32,
       33,   34,   35,   33,   33,   36,   33,   33,   37,   38,
       33,   33,   39,   33,   33,   33,   33,   40,   41,   33,
        1,    1,    1,    1,   42,    1,   43,   44,   45,   46,

       47,   48,   49,   50,   51,   33,   33,   52,   33,   53,
       54,   33,   33,   55,   56,   57,   33,   33,   33,   58,
       59,   33,    1,   60,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[61] =
    {   0,
        1,    2,    3,    4,    1,    5,    1,    6,    6,    6,
        7,    1,    6,    8,    1,    9,    9,    9,    9,    9,
       10,    1,    1,    1,    1,   10,   11,   11,   11,   11,
       11,   11,   12,   12,   12,   12,   12,   12,   12,   12,
       12,   13,   11,   11,   11,   11,   11,   11,   12,   12,
       12,   12,   12,   12,   12,   12,   12,   12,   12,    1
    } ;

static yyconst short int yy_base[228] =
    {   0,
        0,    0,   59,   64,   69,   72,   75,   80,   85,   88,
       92,    0,  148,    0,  185,  192,  233,    0,  293,  353,
      523,  851,  153,  851,  851,    0,  148,  163,  293,  312,
      310,  323,  197,  495,  851,    0,    0,  494,    0,  851,
      851,  466,  459,   16,  455,  457,    0,    0,    0,  182,
      851,    0,  851,  851,  851,  851,  372,  483,  851,  412,
      367,  387,  403,  470,  473,    0,  467,  134,    0,    0,
        0,  158,  490,  156,  449,  133,  476,  211,  851,  851,
      851,  296,  475,  474,  473,  436,  851,  851,  466,  455,
      851,  851,    0,  471,  469,  468,    0,  218,    0,  181,

      328,  331,  851,  851,  851,  851,    0,   59,  194,  467,
        0,    0,  851,  851,  851,  851,  444,  434,  851,  427,
      431,  473,    0,    0,  382,    0,  399,  851,  535,    0,
      434,    0,    0,  432,  391,  450,  433,  474,  851,  851,
      851,  397,  385,  851,  851,  851,  851,  851,  851,  851,
      851,    0,    0,    0,  135,  376,  851,  366,  369,  411,
      401,  591,  400,  396,  393,  390,  388,  851,  851,  851,
      340,  331,    0,  359,  393,  368,  348,  851,  285,    0,
      320,  310,  203,    0,  851,  195,    0,  851,  851,  851,
      169,  155,    0,  851,    0,  154,  851,  851,  851,  650,

      663,  676,  689,  702,  707,  713,  718,  729,  742,  755,
      768,  771,  775,  780,  785,  790,  800,  806,  815,  817,
      822,  824,  830,  832,  834,  836,  838
    } ;

static yyconst short int yy_def[228] =
    {   0,
      199,    1,  200,  200,  201,  201,  202,  202,  203,  203,
      199,   11,    1,   13,  200,  200,  199,   17,  204,  204,
      199,  199,  199,  199,  199,  205,  199,  199,  199,  206,
      207,  207,   32,   33,  199,  207,  207,  207,  207,  199,
      199,  199,  199,  199,  199,  199,  208,  209,  210,  210,
      199,  211,  199,  199,  199,  199,  206,   33,  199,  199,
       60,   60,   60,   60,   60,  212,  212,  212,  212,  212,
      212,   60,  212,   73,  212,  212,  199,  199,  199,  199,
      199,  199,  199,  199,  199,  199,  199,  199,  199,  199,
      199,  199,  213,  213,  213,  213,  214,  199,  205,  199,

      199,  199,  199,  199,  199,  199,  215,  216,   32,   33,
      207,   32,  199,  199,  199,  199,  199,  199,  199,  199,
      199,  208,  209,  210,  210,  211,  199,  199,  199,  129,
      217,  129,  129,  217,  217,  217,  217,  217,  199,  199,
      199,  199,  199,  199,  199,  199,  199,  199,  199,  199,
      199,  213,  214,  215,  216,  199,  199,  199,  199,  208,
      218,  199,  219,  219,  219,  219,  219,  199,  199,  199,
      199,  199,  220,  221,  199,  207,  199,  199,  199,  222,
      223,  199,  199,  224,  199,  199,  225,  199,  199,  199,
      199,  199,  226,  199,  227,  199,  199,  199,    0,  199,

      199,  199,  199,  199,  199,  199,  199,  199,  199,  199,
      199,  199,  199,  199,  199,  199,  199,  199,  199,  199,
      199,  199,  199,  199,  199,  199,  199
    } ;

static yyconst short int yy_nxt[912] =
    {   0,
       22,   23,   24,   23,   22,   25,   22,   26,   27,   28,
       22,   22,   29,   22,   30,   31,   32,   31,   33,   34,
       22,   35,   22,   22,   22,   22,   36,   37,   38,   39,
       36,   36,   22,   40,   22,   22,   41,   22,   22,   22,
       22,   22,   36,   36,   38,   36,   36,   36,   22,   22,
       42,   43,   22,   44,   22,   45,   46,   22,   22,   22,
       23,   24,   23,  118,   47,   23,   24,   23,  119,   47,
       23,   24,   23,   23,   24,   23,   50,   24,   50,  154,
       51,   50,   24,   50,  154,   51,   23,   24,   23,   23,
       24,   23,   22,   23,   24,   23,   22,   22,   53,   26,

       27,   28,   54,   55,   29,   56,   57,   31,   32,   31,
       58,   58,   59,   22,   22,   22,   22,   22,   60,   61,
       62,   63,   64,   65,   66,   67,   68,   69,   66,   66,
       66,   70,   71,   22,   72,   73,   62,   74,   64,   65,
       66,   75,   76,   69,   66,   66,   66,   66,   66,   70,
       71,   22,   77,   22,   98,  154,   98,   78,   79,   80,
      154,   81,   82,  100,  100,  198,   58,   58,  195,   22,
       83,   84,   85,  135,  136,   36,   36,   36,  101,  101,
      101,   22,  194,  125,   22,  125,   23,   24,   23,  129,
      137,  138,   36,   23,   24,   23,  100,  100,   22,   22,

      129,   22,  133,   22,   22,  130,  192,   86,   87,  109,
      109,   88,  110,  110,  110,   87,  190,  113,   88,   98,
      140,   98,   89,   90,   91,   92,  101,  101,  101,   89,
       90,   91,   92,   22,   23,   24,   23,   22,   22,   22,
       22,   22,   22,   22,   22,   22,   22,   22,   93,   93,
       93,   94,   95,   22,   22,   22,   22,   22,   22,   93,
       93,   96,   93,   93,   93,   93,   93,   93,   93,   93,
       93,   93,   93,   93,   93,   93,   93,   96,   93,   93,
       93,   93,   93,   93,   93,   93,   93,   93,   93,   93,
       93,   93,   22,   22,   23,   24,   23,   22,   22,   22,

       22,   22,   22,   22,   22,   22,   22,   22,  102,  102,
      102,  102,  102,   22,   22,   22,   22,   22,   22,  103,
      104,  105,  141,  189,  106,  109,  109,  109,  110,  110,
      187,  185,  107,  142,  143,  144,  145,  107,  112,  112,
      109,  110,  110,  101,  101,  101,  102,  102,  102,  102,
      102,  184,   22,   22,   23,   24,   23,   22,   22,   22,
       22,   22,   22,   22,   22,   22,   22,   22,  199,  199,
      199,  184,  181,   22,   22,   22,   22,   22,   22,  199,
      199,  199,  179,  125,  199,  125,  178,  199,  199,  199,
      199,  175,  107,  175,  161,  132,  175,  107,  129,  175,

      127,  128,  127,  175,  199,  199,  199,  199,  183,  183,
      183,  173,   22,  127,  128,  127,  160,  172,  129,  128,
      171,  170,  169,  199,  164,  168,  165,  111,  111,  111,
      111,  111,  128,  133,  129,  161,  161,  161,  129,  129,
      129,  129,  129,  130,  131,  131,  131,  131,  131,  131,
      131,  131,  131,  161,  129,  129,  129,  129,  129,  129,
      131,  131,  131,  131,  131,  131,  131,  131,  131,  131,
      131,  199,  199,  199,  199,  199,  199,  161,  160,  159,
      158,  157,  164,  166,  165,  167,  156,  199,  115,  114,
      199,  113,  151,  199,  150,  149,  148,  147,  146,  139,

      134,  129,  134,  199,  129,  111,  111,  111,  111,  111,
      121,  120,  117,  116,  115,  114,  129,  129,  129,  129,
      129,  129,  199,  166,  199,  167,  199,  199,  199,  199,
      199,  199,  129,  129,  132,  129,  129,  129,  161,  199,
      199,  199,  199,  199,  199,  199,  199,  199,  199,  199,
      111,  111,  111,  111,  111,  199,  199,  199,  199,  199,
      199,  162,  162,  162,  162,  162,  162,  163,  163,  163,
      163,  163,  163,  163,  163,  163,  199,  162,  162,  162,
      162,  162,  162,  163,  163,  163,  163,  163,  163,  163,
      163,  163,  163,  163,  175,  199,  199,  199,  199,  199,

      199,  199,  199,  199,  199,  199,  111,  111,  111,  111,
      111,  199,  199,  199,  199,  199,  199,  176,  176,  176,
      176,  176,  176,  177,  177,  177,  177,  177,  177,  177,
      177,  177,  199,  176,  176,  176,  176,  176,  176,  177,
      177,  177,  177,  177,  177,  177,  177,  177,  177,  177,
       22,   22,   22,   22,   22,   22,   22,   22,   22,   22,
       22,   22,   22,   48,   48,   48,   48,   48,   48,   48,
       48,   48,   48,   48,   48,   48,   49,   49,   49,   49,
       49,   49,   49,   49,   49,   49,   49,   49,   49,   52,
       52,   52,   52,   52,   52,   52,   52,   52,   52,   52,

       52,   52,   97,   97,   97,   97,   97,   97,   97,   97,
       97,   97,   97,   97,   97,   99,  199,   99,  108,  199,
      199,  199,  108,  108,  108,  108,  111,  199,  111,  122,
      122,  199,  122,  122,  122,  122,  122,  122,  122,  122,
      122,  122,  123,  199,  199,  199,  123,  123,  123,  123,
      123,  123,  123,  123,  123,  124,  124,  199,  124,  199,
      124,  124,  124,  124,  124,  124,  124,  124,  126,  126,
      199,  126,  126,  126,  126,  126,  126,  126,  126,  126,
      126,  131,  131,  152,  199,  152,  152,  152,  153,  199,
      153,  153,  153,  154,  154,  154,  154,  154,  155,  155,

      155,  155,  155,  163,  199,  199,  199,  199,  199,  199,
      163,  163,  174,  199,  199,  199,  174,  174,  177,  199,
      199,  199,  199,  199,  199,  177,  177,  180,  180,  182,
      199,  199,  182,  182,  186,  186,  188,  199,  199,  199,
      188,  188,  191,  191,  193,  193,  196,  196,  197,  197,
       21,  199,  199,  199,  199,  199,  199,  199,  199,  199,
      199,  199,  199,  199,  199,  199,  199,  199,  199,  199,
      199,  199,  199,  199,  199,  199,  199,  199,  199,  199,
      199,  199,  199,  199,  199,  199,  199,  199,  199,  199,
      199,  199,  199,  199,  199,  199,  199,  199,  199,  199,

      199,  199,  199,  199,  199,  199,  199,  199,  199,  199,
      199
    } ;

static yyconst short int yy_chk[912] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        3,    3,    3,   44,    3,    4,    4,    4,   44,    4,
        5,    5,    5,    6,    6,    6,    7,    7,    7,  108,
        7,    8,    8,    8,  108,    8,    9,    9,    9,   10,
       10,   10,   11,   11,   11,   11,   11,   11,   11,   11,

       11,   11,   11,   11,   11,   11,   11,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,   11,   11,   11,
       11,   11,   13,   13,   23,  155,   23,   13,   13,   13,
      155,   13,   13,   27,   27,  196,   13,   13,  192,   13,
       13,   13,   13,   68,   68,   13,   13,   13,   28,   28,
       28,   13,  191,   50,   13,   50,   15,   15,   15,   72,
       76,   76,   13,   16,   16,   16,  100,  100,   13,   13,

       74,   13,   74,   13,   13,   72,  186,   13,   15,  109,
      109,   15,   33,   33,   33,   16,  183,   33,   16,   98,
       78,   98,   15,   15,   15,   15,   78,   78,   78,   16,
       16,   16,   16,   17,   17,   17,   17,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   17,   17,   17,
       17,   17,   17,   19,   19,   19,   19,   19,   19,   19,

       19,   19,   19,   19,   19,   19,   19,   19,   29,   29,
       29,   29,   29,   19,   19,   19,   19,   19,   19,   30,
       30,   30,   82,  182,   30,   31,   31,   31,   31,   31,
      181,  179,   30,   82,   82,   82,   82,   30,   32,   32,
       32,   32,   32,  101,  101,  101,  102,  102,  102,  102,
      102,  177,   19,   20,   20,   20,   20,   20,   20,   20,
       20,   20,   20,   20,   20,   20,   20,   20,   61,   61,
       61,  176,  174,   20,   20,   20,   20,   20,   20,   57,
       57,   57,  172,  125,   57,  125,  171,   61,   62,   62,
       62,  167,   57,  166,  135,   61,  165,   57,   61,  164,

      127,  127,  127,  163,   63,   63,   63,   62,  175,  175,
      175,  161,   20,   60,   60,   60,  160,  159,   62,  127,
      158,  156,  143,   63,  135,  142,  135,   60,   60,   60,
       60,   60,   60,   63,   63,  134,  137,  131,   60,   60,
       60,   60,   60,   60,   60,   60,   60,   60,   60,   60,
       60,   60,   60,  136,   60,   60,   60,   60,   60,   60,
       60,   60,   60,   60,   60,   60,   60,   60,   60,   60,
       60,   64,   64,   64,   65,   65,   65,  138,  122,  121,
      120,  118,  137,  136,  137,  136,  117,  110,   96,   95,
       64,   94,   90,   65,   89,   86,   85,   84,   83,   77,

       75,   64,   67,   58,   65,   73,   73,   73,   73,   73,
       46,   45,   43,   42,   38,   34,   73,   73,   73,   73,
       73,   73,   21,  138,    0,  138,    0,    0,    0,    0,
        0,    0,   73,   73,   73,   73,   73,   73,  129,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
      129,  129,  129,  129,  129,    0,    0,    0,    0,    0,
        0,  129,  129,  129,  129,  129,  129,  129,  129,  129,
      129,  129,  129,  129,  129,  129,    0,  129,  129,  129,
      129,  129,  129,  129,  129,  129,  129,  129,  129,  129,
      129,  129,  129,  129,  162,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,  162,  162,  162,  162,
      162,    0,    0,    0,    0,    0,    0,  162,  162,  162,
      162,  162,  162,  162,  162,  162,  162,  162,  162,  162,
      162,  162,    0,  162,  162,  162,  162,  162,  162,  162,
      162,  162,  162,  162,  162,  162,  162,  162,  162,  162,
      200,  200,  200,  200,  200,  200,  200,  200,  200,  200,
      200,  200,  200,  201,  201,  201,  201,  201,  201,  201,
      201,  201,  201,  201,  201,  201,  202,  202,  202,  202,
      202,  202,  202,  202,  202,  202,  202,  202,  202,  203,
      203,  203,  203,  203,  203,  203,  203,  203,  203,  203,

      203,  203,  204,  204,  204,  204,  204,  204,  204,  204,
      204,  204,  204,  204,  204,  205,    0,  205,  206,    0,
        0,    0,  206,  206,  206,  206,  207,    0,  207,  208,
      208,    0,  208,  208,  208,  208,  208,  208,  208,  208,
      208,  208,  209,    0,    0,    0,  209,  209,  209,  209,
      209,  209,  209,  209,  209,  210,  210,    0,  210,    0,
      210,  210,  210,  210,  210,  210,  210,  210,  211,  211,
        0,  211,  211,  211,  211,  211,  211,  211,  211,  211,
      211,  212,  212,  213,    0,  213,  213,  213,  214,    0,
      214,  214,  214,  215,  215,  215,  215,  215,  216,  216,

      216,  216,  216,  217,    0,    0,    0,    0,    0,    0,
      217,  217,  218,    0,    0,    0,  218,  218,  219,    0,
        0,    0,    0,    0,    0,  219,  219,  220,  220,  221,
        0,    0,  221,  221,  222,  222,  223,    0,    0,    0,
      223,  223,  224,  224,  225,  225,  226,  226,  227,  227,
      199,  199,  199,  199,  199,  199,  199,  199,  199,  199,
      199,  199,  199,  199,  199,  199,  199,  199,  199,  199,
      199,  199,  199,  199,  199,  199,  199,  199,  199,  199,
      199,  199,  199,  199,  199,  199,  199,  199,  199,  199,
      199,  199,  199,  199,  199,  199,  199,  199,  199,  199,

      199,  199,  199,  199,  199,  199,  199,  199,  199,  199,
      199
    } ;

static yy_state_type yy_state_buf[YY_BUF_SIZE + 2], *yy_state_ptr;
static char *yy_full_match;
static int yy_lp;
static int yy_looking_for_trail_begin = 0;
static int yy_full_lp;
static int *yy_full_state;
#define YY_TRAILING_MASK 0x2000
#define YY_TRAILING_HEAD_MASK 0x4000
#define REJECT \
{ \
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */ \
yy_cp = yy_full_match; /* restore poss. backed-over text */ \
yy_lp = yy_full_lp; /* restore orig. accepting pos. */ \
yy_state_ptr = yy_full_state; /* restore orig. state */ \
yy_current_state = *yy_state_ptr; /* restore curr. state */ \
++yy_lp; \
goto find_rule; \
}
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "mon_lex.l"
#define INITIAL 0
/* -*- C -*-
 *
 * mon_lex.l - Lexer for the VICE built-in monitor.
 *
 * Written by
 *  Daniel Sladic <sladic@eecg.toronto.edu>
 *  Andreas Boose <viceteam@t-online.de>
 *
 * This file is part of VICE, the Versatile Commodore Emulator.
 * See README for copyright notice.
 *
 *  This program is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation; either version 2 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program; if not, write to the Free Software
 *  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA
 *  02111-1307  USA.
 *
 */
#line 30 "mon_lex.l"

/* Lexer for x64 monitor */

#include "vice.h"

#include <assert.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "mon_command.h"
#include "montypes.h"
#include "mon_parse.h" /* FIXME ! */
#include "utils.h"
#include "types.h"

#undef min
#define min(a,b) ((a) < (b) ? (a) : (b))

int new_cmd = 1, quote = 0, opt_asm = 0, cur_len = 0, last_len = 0, dont_match_reg_a = 0;
int temp, push_back;
static int yywrap(void);
YY_BUFFER_STATE my_state;

#define YY_USER_ACTION { last_len = cur_len; cur_len += yyleng; }

#define FNAME 1
#define CMD 2
#define STR 3
#define ROL 4
#define ASM_MODE 5
#define COND_MODE 6
#define REG_ASGN 7
#define BNAME 8
#define CTYPE 9

#line 757 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 60 "mon_lex.l"



   if (new_cmd) {
      if (!(asm_mode && opt_asm))
         last_len = cur_len = 0;

      if (asm_mode) {
         BEGIN (ASM_MODE);
         opt_asm = 0;
      } else
         BEGIN (CMD);
      new_cmd = 0;
   }


#line 925 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
		yy_state_ptr = yy_state_buf;
		*yy_state_ptr++ = yy_current_state;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 200 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			*yy_state_ptr++ = yy_current_state;
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 851 );

yy_find_action:
		yy_current_state = *--yy_state_ptr;
		yy_lp = yy_accept[yy_current_state];
find_rule: /* we branch to this label when backing up */
		for ( ; ; ) /* until we find what rule we matched */
			{
			if ( yy_lp && yy_lp < yy_accept[yy_current_state + 1] )
				{
				yy_act = yy_acclist[yy_lp];
				if ( yy_act & YY_TRAILING_HEAD_MASK ||
				     yy_looking_for_trail_begin )
					{
					if ( yy_act == yy_looking_for_trail_begin )
						{
						yy_looking_for_trail_begin = 0;
						yy_act &= ~YY_TRAILING_HEAD_MASK;
						break;
						}
					}
				else if ( yy_act & YY_TRAILING_MASK )
					{
					yy_looking_for_trail_begin = yy_act & ~YY_TRAILING_MASK;
					yy_looking_for_trail_begin |= YY_TRAILING_HEAD_MASK;
					}
				else
					{
					yy_full_match = yy_cp;
					yy_full_state = yy_state_ptr;
					yy_full_lp = yy_lp;
					break;
					}
				++yy_lp;
				goto find_rule;
				}
			--yy_cp;
			yy_current_state = *--yy_state_ptr;
			yy_lp = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
case 1:
YY_RULE_SETUP
#line 76 "mon_lex.l"
{ push_back = 0;
                   if ( (temp = mon_command_lookup_index(yytext, &push_back)) < 0) {
                      return BAD_CMD;
                   } else {
                      if (push_back)
                         yyless(push_back);

                      switch(mon_command_get_next_state(temp)) {
                         case STATE_INITIAL:
                            BEGIN (INITIAL);
                            break;
                         case STATE_FNAME:
                            BEGIN (FNAME);
                            break;
                         case STATE_BNAME:
                            BEGIN (BNAME);
                            break;
                         case STATE_CTYPE:
                            BEGIN (CTYPE);
                            break;
                         case STATE_ROL:
                            BEGIN (ROL);
                            break;
                         case STATE_REG_ASGN:
                            BEGIN (REG_ASGN);
                            break;
                         default:
                            assert(0);
                      }
                      yylval.i = mon_command_get_token(temp);
                      if (yylval.i == CMD_ASSEMBLE)
                         opt_asm = 1;
                      return yylval.i;
                   }
                 } 
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 112 "mon_lex.l"
{ new_cmd = 1; return CMD_SEP; }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 114 "mon_lex.l"
{ yylval.i = e_ON; return TOGGLE; }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 115 "mon_lex.l"
{ yylval.i = e_OFF; return TOGGLE; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 116 "mon_lex.l"
{ yylval.i = e_TOGGLE; return TOGGLE; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 118 "mon_lex.l"
{ yylval.i = e_load; return MEM_OP; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 119 "mon_lex.l"
{ yylval.i = e_store; return MEM_OP; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 121 "mon_lex.l"
{ BEGIN (COND_MODE); return IF; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 123 "mon_lex.l"
{ if (!quote) {
                     quote = 1;
                     BEGIN (STR);
                  }
                }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 128 "mon_lex.l"
{ if (quote) {
                     quote = 0;
                     BEGIN (INITIAL);
                  }
                }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 134 "mon_lex.l"
{ yylval.str = stralloc(yytext); return STRING; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 137 "mon_lex.l"
{ yylval.i = e_hexadecimal; return INPUT_SPEC; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 138 "mon_lex.l"
{ yylval.i = e_decimal; return INPUT_SPEC; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 139 "mon_lex.l"
{ yylval.i = e_binary; return INPUT_SPEC; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 140 "mon_lex.l"
{ yylval.i = e_octal; return INPUT_SPEC; }
	YY_BREAK
/* \.TA		{ yylval.i = e_text_ascii; return INPUT_SPEC; } */
/* \.TP		{ yylval.i = e_text_petscii; return INPUT_SPEC; } */
/* \.\>		{ yylval.i = e_6502_asm; return INPUT_SPEC; } */
/* \.S		{ yylval.i = e_sprite; return INPUT_SPEC; } */
/* \.C		{ yylval.i = e_character; return INPUT_SPEC; } */
case 16:
YY_RULE_SETUP
#line 147 "mon_lex.l"
{ yylval.i = e_decimal; return RADIX_TYPE; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 148 "mon_lex.l"
{ yylval.i = e_hexadecimal; return RADIX_TYPE; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 149 "mon_lex.l"
{ yylval.i = e_binary; return RADIX_TYPE; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 150 "mon_lex.l"
{ yylval.i = e_octal; return RADIX_TYPE; }
	YY_BREAK
/* C		{ yylval.i = e_character; return RADIX_TYPE; } */
/* S		{ yylval.i = e_sprite; return RADIX_TYPE; } */
/* TA		{ yylval.i = e_text_ascii; return RADIX_TYPE; } */
/* TP		{ yylval.i = e_text_petscii; return RADIX_TYPE; } */
case 20:
YY_RULE_SETUP
#line 156 "mon_lex.l"
{ return MEM_COMP; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 157 "mon_lex.l"
{ return MEM_DISK8; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 158 "mon_lex.l"
{ return MEM_DISK9; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 160 "mon_lex.l"
{ yylval.str = stralloc(yytext); return CPUTYPE; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 162 "mon_lex.l"

	YY_BREAK
case 25:
YY_RULE_SETUP
#line 163 "mon_lex.l"
{ dont_match_reg_a = 0;
                 new_cmd = 1;
                 opt_asm = 0;
                 quote = 0;
                 BEGIN(INITIAL);
                 return TRAIL;
               }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 171 "mon_lex.l"
{ yytext[yyleng-1] = '\0';
                yylval.str = stralloc(yytext+1);
                BEGIN (INITIAL); return FILENAME; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 175 "mon_lex.l"
{ yylval.str = stralloc(yytext); return BANKNAME; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 177 "mon_lex.l"
{ yylval.str = stralloc(yytext); return R_O_L; }
	YY_BREAK

case 29:
YY_RULE_SETUP
#line 180 "mon_lex.l"
{ yylval.i = e_A; return REGISTER; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 181 "mon_lex.l"
{ yylval.i = e_X; return REGISTER; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 182 "mon_lex.l"
{ yylval.i = e_Y; return REGISTER; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 183 "mon_lex.l"
{ yylval.i = e_PC; return REGISTER; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 184 "mon_lex.l"
{ yylval.i = e_SP; return REGISTER; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 185 "mon_lex.l"
{ BEGIN (COND_MODE); return EQUALS; }
	YY_BREAK


case 35:
YY_RULE_SETUP
#line 189 "mon_lex.l"
{ yylval.i = e_EQU; return COMPARE_OP; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 190 "mon_lex.l"
{ yylval.i = e_NEQ; return COMPARE_OP; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 191 "mon_lex.l"
{ yylval.i = e_LTE; return COMPARE_OP; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 192 "mon_lex.l"
{ yylval.i = e_LT;  return COMPARE_OP; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 193 "mon_lex.l"
{ yylval.i = e_GT;  return COMPARE_OP; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 194 "mon_lex.l"
{ yylval.i = e_GTE; return COMPARE_OP; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 195 "mon_lex.l"
{ yylval.i = e_AND; return COMPARE_OP; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 196 "mon_lex.l"
{ yylval.i = e_OR;  return COMPARE_OP; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 198 "mon_lex.l"
{ yylval.i = e_A; return REGISTER; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 199 "mon_lex.l"
{ yylval.i = e_X; return REGISTER; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 200 "mon_lex.l"
{ yylval.i = e_Y; return REGISTER; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 201 "mon_lex.l"
{ yylval.i = e_PC; return REGISTER; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 202 "mon_lex.l"
{ yylval.i = e_SP; return REGISTER; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 204 "mon_lex.l"
{ BEGIN (REG_ASGN); return REG_ASGN_SEP; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 205 "mon_lex.l"
{ return L_PAREN; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 206 "mon_lex.l"
{ return R_PAREN; }
	YY_BREAK

case 51:
YY_RULE_SETUP
#line 209 "mon_lex.l"
{
    yylval.str = stralloc(yytext); return OPCODE; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 211 "mon_lex.l"
{
    yylval.str = stralloc(yytext); return OPCODE; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 213 "mon_lex.l"
{
    yylval.str = stralloc(yytext); return OPCODE; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 215 "mon_lex.l"
{
    yylval.str = stralloc(yytext); return OPCODE; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 217 "mon_lex.l"
{
    yylval.str = stralloc(yytext); return OPCODE; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 219 "mon_lex.l"
{
    yylval.str = stralloc(yytext); return OPCODE; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 221 "mon_lex.l"
{
    yylval.str = stralloc(yytext); return OPCODE; }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 223 "mon_lex.l"
{
    yylval.str = stralloc(yytext); return OPCODE; }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 225 "mon_lex.l"
{ return REG_AF; }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 226 "mon_lex.l"
{ return REG_BC; }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 227 "mon_lex.l"
{ return REG_DE; }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 228 "mon_lex.l"
{ return REG_HL; }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 229 "mon_lex.l"
{ return REG_IX; }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 230 "mon_lex.l"
{ return REG_IXH; }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 231 "mon_lex.l"
{ return REG_IXL; }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 232 "mon_lex.l"
{ return REG_IY; }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 233 "mon_lex.l"
{ return REG_IYH; }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 234 "mon_lex.l"
{ return REG_IYL; }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 235 "mon_lex.l"
{ yylval.str = stralloc(yytext); return OPCODE; }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 236 "mon_lex.l"
{ yylval.str = stralloc(yytext); return LABEL; }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 237 "mon_lex.l"
{ yylval.str = stralloc(yytext); return LABEL; }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 239 "mon_lex.l"
{ if (!dont_match_reg_a) return REG_A;
                                        yylval.i = 0x0a; return H_NUMBER; }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 241 "mon_lex.l"
{ return REG_B; }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 242 "mon_lex.l"
{ return REG_C; }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 243 "mon_lex.l"
{ return REG_D; }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 244 "mon_lex.l"
{ return REG_E; }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 245 "mon_lex.l"
{ return REG_H; }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 246 "mon_lex.l"
{ return REG_L; }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 247 "mon_lex.l"
{ return REG_X; }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 248 "mon_lex.l"
{ return REG_Y; }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 250 "mon_lex.l"
{ return COMMA; }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 251 "mon_lex.l"
{ dont_match_reg_a = 1; return L_PAREN; }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 252 "mon_lex.l"
{ dont_match_reg_a = 0; return R_PAREN; }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 253 "mon_lex.l"
{ dont_match_reg_a = 1; return ARG_IMMEDIATE; }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 254 "mon_lex.l"
{ dont_match_reg_a = 0; return INST_SEP; }
	YY_BREAK

case 86:
YY_RULE_SETUP
#line 257 "mon_lex.l"
{ yylval.str = stralloc(yytext); return B_NUMBER_GUESS; }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 258 "mon_lex.l"
{ yylval.i = strtol(yytext+1, NULL, 2); return B_NUMBER; }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 259 "mon_lex.l"
{ yylval.i = strtol(yytext+1, NULL, 8); return O_NUMBER; }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 260 "mon_lex.l"
{ yylval.str = stralloc(yytext); return O_NUMBER_GUESS; }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 261 "mon_lex.l"
{ yylval.i = strtol(yytext+1, NULL, 10); return D_NUMBER; }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 262 "mon_lex.l"
{ yylval.str = stralloc(yytext); return D_NUMBER_GUESS; }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 263 "mon_lex.l"
{ yylval.i = strtol(yytext+1, NULL, 16); return H_NUMBER; }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 264 "mon_lex.l"
{ yylval.i = strtol(yytext, NULL, 16); return H_NUMBER; }
	YY_BREAK

case 94:
YY_RULE_SETUP
#line 267 "mon_lex.l"
{ return yytext[0]; }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 269 "mon_lex.l"
ECHO;
	YY_BREAK
#line 1578 "lex.yy.c"
			case YY_STATE_EOF(INITIAL):
			case YY_STATE_EOF(FNAME):
			case YY_STATE_EOF(CMD):
			case YY_STATE_EOF(STR):
			case YY_STATE_EOF(ROL):
			case YY_STATE_EOF(ASM_MODE):
			case YY_STATE_EOF(COND_MODE):
			case YY_STATE_EOF(REG_ASGN):
			case YY_STATE_EOF(BNAME):
			case YY_STATE_EOF(CTYPE):
				yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;
	yy_state_ptr = yy_state_buf;
	*yy_state_ptr++ = yy_current_state;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 200 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		*yy_state_ptr++ = yy_current_state;
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;

	register YY_CHAR yy_c = 1;
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 200 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 199);
	if ( ! yy_is_jam )
		*yy_state_ptr++ = yy_current_state;

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 269 "mon_lex.l"


void free_buffer(void)
{
   yy_delete_buffer(my_state);
}

void make_buffer(char *str)
{
    my_state = yy_scan_buffer(str, strlen(str) + 2);
    assert(my_state);
}

static int yywrap(void)
{
    return 1;
}

